//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_FARMACIAEntities3 : DbContext
    {
        public BD_FARMACIAEntities3()
            : base("name=BD_FARMACIAEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_LABORATORIO> TB_LABORATORIO { get; set; }
        public virtual DbSet<TB_MEDICAMENTOS> TB_MEDICAMENTOS { get; set; }
    }
}
