//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_LABORATORIO
    {
        [Required(ErrorMessage = "El campo NOMBRE es requerido")]
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string CUIT { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
    }
}
