//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.Models
{
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_MEDICAMENTOS
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "El campo NOMBRE es requerido")]
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string GRAMAJE { get; set; }
        public string TIPO_PASTILLAS { get; set; }

        [StringLength(1, ErrorMessage = "El campo DOBLE RECETA debe contener solo 1 caracter.")]
        public string DOBLE_RECETA { get; set; }
        public string PRESENTACION { get; set; }
        public string LABORATORIO { get; set; }
    }
}
